# Generated by Django 5.2.5 on 2025-08-14 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('case_type', models.CharField(choices=[('ASSAULT', 'Assault'), ('GBV', 'Gender-Based Violence'), ('HOMICIDE', 'Homicide / Murder'), ('MISSING_PERSON', 'Missing Person'), ('SUICIDE', 'Suicide / Attempted Suicide'), ('THEFT', 'Theft'), ('ROBBERY', 'Robbery'), ('BURGLARY', 'Burglary / Break-in'), ('ARSON', 'Arson'), ('FRAUD', 'Fraud'), ('CORRUPTION', 'Corruption / Bribery'), ('TRAFFIC', 'Traffic Offense'), ('PUBLIC_DISTURBANCE', 'Public Disturbance'), ('ILLEGAL_ASSEMBLY', 'Illegal Assembly / Protest'), ('DRUG_POSSESSION', 'Drug Possession / Trafficking'), ('ILLEGAL_WEAPONS', 'Illegal Possession of Firearms / Weapons'), ('DOMESTIC', 'Domestic Dispute'), ('CHILD_ABUSE', 'Child Abuse / Neglect'), ('LOST_PROPERTY', 'Lost Property'), ('RECOVERED_PROPERTY', 'Recovered Property'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bail_decision', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('in_court', 'In Court'), ('closed', 'Closed'), ('dismissed', 'Dismissed')], default='open', max_length=30)),
                ('court_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_reported', to=settings.AUTH_USER_MODEL)),
                ('complainant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.complainant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
