# Generated by Django 5.2.5 on 2025-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('arrest_date', models.DateField(blank=True, null=True)),
                ('charges', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='suspects',
            field=models.ManyToManyField(blank=True, related_name='cases', to='cases.suspect'),
        ),
        migrations.AddField(
            model_name='case',
            name='witnesses',
            field=models.ManyToManyField(blank=True, related_name='cases', to='cases.witness'),
        ),
    ]
