# Generated by Django 5.2.5 on 2025-08-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_suspect_witness_case_incident_date_case_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='witness',
            options={'verbose_name_plural': 'Witnesses'},
        ),
        migrations.AddField(
            model_name='suspect',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='witness',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='witness',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='witness',
            name='date_of_statement',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
