# Generated by Django 5.2.5 on 2025-08-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_witness_options_suspect_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='date_of_statement',
            field=models.DateField(auto_now_add=True),
        ),
    ]
