# Generated by Django 5.2.5 on 2025-08-15 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_witness_date_of_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
