# Generated by Django 5.2.5 on 2025-08-15 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
