# Generated by Django 5.2.5 on 2025-08-15 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
