# Generated by Django 5.2.5 on 2025-08-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainant',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
