# Generated by Django 5.2.5 on 2025-08-18 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_complainant_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
