# Generated by Django 5.2.5 on 2025-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_case_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='report_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
