# Generated by Django 5.2.5 on 2025-08-18 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_case_report_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('decision_type', models.CharField(choices=[('BAIL_GRANTED', 'Bail Granted'), ('BAIL_DENIED', 'Bail Denied'), ('DISMISSED', 'Case Dismissed'), ('SENTENCED', 'Sentenced'), ('ADJOURNED', 'Adjourned'), ('OTHER', 'Other')], max_length=20)),
                ('decision_text', models.TextField()),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_decisions', to='cases.case')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decision_date'],
            },
        ),
    ]
