# Generated by Django 5.2.5 on 2025-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_courtdecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='bail_decision',
            field=models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20),
        ),
    ]
