# Generated by Django 5.2.5 on 2025-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_alter_case_bail_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
