# Generated by Django 5.2.5 on 2025-08-18 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_suspect_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
