# Generated by Django 5.2.5 on 2025-08-19 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_alter_suspect_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectCourtRuling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ruling_type', models.CharField(choices=[('bail_granted', 'Bail Granted'), ('bail_denied', 'Bail Denied'), ('dismissed', 'Dismissed'), ('sentenced', 'Sentenced'), ('acquitted', 'Acquitted'), ('adjourned', 'Adjourned')], max_length=20)),
                ('ruling_text', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='cases.case')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='cases.suspect')),
            ],
            options={
                'unique_together': {('suspect', 'case', 'ruling_type')},
            },
        ),
    ]
