# Generated by Django 5.2.5 on 2025-08-19 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_suspectcourtruling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='arrest_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='bail_status',
            field=models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='suspect',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspects_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspect',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='statement_date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='courtdecision',
            name='decision_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courtdecision',
            name='decision_type',
            field=models.CharField(choices=[('DISMISSED', 'Case Dismissed'), ('ADJOURNED', 'Adjourned'), ('TRANSFERRED', 'Transferred'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courtdecision',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
