# Generated by Django 5.2.5 on 2025-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_suspect_arrest_location_suspect_bail_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='statement_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
