# Generated by Django 5.2.5 on 2025-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_alter_suspect_statement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectcourtruling',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
