# Generated by Django 5.2.5 on 2025-08-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_suspectcourtruling_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
