# Generated by Django 5.2.5 on 2025-08-19 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_witness_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
