# Generated by Django 5.2.5 on 2025-08-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_alter_witness_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='bail_decision',
        ),
    ]
