# Generated by Django 5.2.5 on 2025-08-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_remove_case_bail_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspectcourtruling',
            name='ruling_type',
            field=models.CharField(choices=[('bail_granted', 'Bail Granted'), ('bail_denied', 'Bail Denied'), ('fined', 'Fined'), ('dismissed', 'Dismissed'), ('sentenced', 'Sentenced'), ('acquitted', 'Acquitted'), ('adjourned', 'Adjourned')], max_length=20),
        ),
    ]
