# Generated by Django 5.2.5 on 2025-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_alter_suspectcourtruling_ruling_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtdecision',
            name='decision_type',
            field=models.CharField(choices=[('CLoSED', 'Case Closed'), ('DISMISSED', 'Case Dismissed'), ('ADJOURNED', 'Case Adjourned'), ('TRANSFERRED', 'Case Transferred'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
