# Generated by Django 5.2.5 on 2025-08-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_alter_courtdecision_decision_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('in_court', 'In Court'), ('closed', 'Closed'), ('dismissed', 'Dismissed'), ('transferred', 'Transferred')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='courtdecision',
            name='decision_type',
            field=models.CharField(choices=[('CLOSED', 'Case Closed'), ('DISMISSED', 'Case Dismissed'), ('ADJOURNED', 'Case Adjourned'), ('TRANSFERRED', 'Case Transferred'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
