# Generated by Django 5.2.5 on 2025-08-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_alter_case_status_alter_courtdecision_decision_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
