# Generated by Django 5.2.5 on 2025-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_suspect_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainant',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
