# Generated by Django 5.2.5 on 2025-08-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_complainant_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
