# Generated by Django 5.2.5 on 2025-08-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_witness_created_at_witness_recorded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='witness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
