# Generated by Django 5.2.5 on 2025-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_alter_witness_created_at_alter_witness_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
