# Generated by Django 5.2.5 on 2025-08-30 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supportrequest_status_supportrequest_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
